### PR TITLE
New fusion solar api

### PR DESCRIPTION
**Pull request by tijsverkoyen**
The kiosk has been changed, so the data should be retrieved from another endpoint

### CODE REVIEW

**Comment by darksideonDM** [comment]
tell me how often data is downloaded in your kiosk view integration?

**Comment by tijsverkoyen** [comment]
> tell me how often data is downloaded in your kiosk view integration?

Every 5 minutes, it is set in https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk/blob/master/custom_components/fusion_solar_kiosk/sensor.py#L51 (300 seconds)

**Comment by McVillano** [comment]
> > tell me how often data is downloaded in your kiosk view integration?
> 
> Every 5 minutes, it is set in https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk/blob/master/custom_components/fusion_solar_kiosk/sensor.py#L51 (300 seconds)

Is it ok to change it to 60s or 30s to get more acurate power generation data?
Will i broke the component? If it's possible, do you plan to add this value as a config value in the sensor?



Thanks in advance

**Comment by tijsverkoyen** [comment]
I will look into it, but at the moment I don't want to hammer the "API" as it is not an official API.

**Comment by McVillano** [comment]
> I will look into it, but at the moment I don't want to hammer the "API" as it is not an official API.

Thanks!

**Pull request merged**
